### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by eduardokum** [toin0u/DigitalOceanV2#92] opened 2015-03-13 14:40 UTC
Has anyone had this issue?

Uncaught exception 'Buzz\Exception\RequestException' with message 'SSL certificate problem: unable to get local issuer certificate'

My test:
include "vendor/autoload.php";

use DigitalOceanV2\Adapter\BuzzAdapter;
use DigitalOceanV2\DigitalOceanV2;

$adapter = new BuzzAdapter('Personal Access Token');
$digitalocean = new DigitalOceanV2($adapter);
$a = $digitalocean->domain();
print_r($a->getAll());

**Comment by olivercarl** [comment] 2015-03-15 09:47
This seems to be a problem of lower layers (curl?), so it would be helpful to know your system configuration (OS, PHP version, etc.)
The error indicates that the client (your PHP application) is unable to verify the certificate provided by Digital Ocean. As nobody else seems to have the issue, I would suspect that you are using some old version of PHP or any other involved component.

**Comment by toin0u** [comment] 2015-03-16 17:59
@eduardokum I've just tested your script and I do not have any issue. I close it as it does not look like to be an issue with the lib as @olivercarl wrote. Feel free to post more info if you need helps :)

**Closed by toin0u** 2015-03-16 17:59 UTC

**Comment by eduardokum** [comment] 2015-03-19 22:06
My php is 5.4 running on a mac os x
I don't understand it. :/

**Comment by toin0u** [comment] 2015-03-20 08:38
I think you need to try a simple cURL against a HTTPS sites.

**Comment by henno** [comment] 2015-04-02 16:33
I'm getting this error, too. 

It appears to occur on latest Xampp (3.2.1) and is caused by the curl version used in that version (7.39). Basically curl does not have access to trusted root certificates which can be separately downloaded from http://curl.haxx.se/docs/caextract.html

There are 2 ways to get by this error: either modify guzzle (or buzz) to stop verifying the SSL certificate (bad) or download the cacerts.pem file from the URL I mentioned above and insert curl.cainfo = "C:\path\to\cacert.pem" to your php.ini (better security wise but requires modifying php.ini which is not always possible).

**Comment by henno** [comment] 2015-04-02 16:58
See these:
http://stackoverflow.com/a/6400746/584750
http://stackoverflow.com/a/16495053/584750
