### ISSUE TITLE
Domain::getAll pagination bug

### ISSUE THREAD

**Issue by sadikoff** [toin0u/DigitalOceanV2#106] opened 2015-08-14 08:19 UTC
DigitalOcean Api has limitation in domain response. It's 200 domains max. In that case we can't get all domains from api, if number is greater than 200. It would be better to rely on API information about domain count and pagination to get all data.

**Comment by plutus78** [comment] 2015-11-30 20:26
oh yes, we need this, too. Very urgent .-(

**Comment by GrahamCampbell** [comment] 2015-12-21 15:28
We're open to PRs. ;)

**Comment by GrahamCampbell** [comment] 2015-12-21 21:45
Not really a bug either. Just a missing feature.

**Comment by GrahamCampbell** [comment] 2015-12-21 21:45
Duplicate of https://github.com/toin0u/DigitalOceanV2/issues/29.

**Closed** 2015-12-21 21:45 UTC
